'use client';
import { useState } from 'react';

type Category={name:string;score:number;explanation:string};
type FlaggedPhrase={phrase:string;problem:string;severity:'Baja'|'Media'|'Alta'};
type IntelligenceModule={id:string;title:string;detected:boolean;risk:number;summary:string;signals:string[];missingInformation:string[];questions:string[]};
type FinancialMath={detected:boolean;amount?:number|null;installment?:number|null;months?:number|null;totalPaid?:number|null;hiddenCost?:number|null;monthlyImpliedRate?:number|null;annualImpliedRate?:number|null;missingFields:string[];warnings:string[];questions:string[];plainEnglish:string};
type PyramidRisk={detected:boolean;risk:number;level:string;signals:string[];explanation:string;questions:string[]};
type AIDetection={detected:boolean;risk:number;confidence:string;signals:string[];explanation:string;questions:string[];legalNote:string};
type LegalGuard={disclaimer:string;prohibitedLanguagePolicy:string;confidence:'Baja'|'Media'|'Alta'};
type Analysis={documentType:string;decisionQuestion:string;score:number;risk:string;confidence:string;summary:string;categoryScores?:Category[];modules?:IntelligenceModule[];flaggedPhrases?:FlaggedPhrase[];issues:string[];questions:string[];missingInformation?:string[];worstReasonableScenario?:string;improved:string;verdict?:string;financialMath?:FinancialMath;pyramidRisk?:PyramidRisk;aiDetection?:AIDetection;legalGuard?:LegalGuard;source?:{kind:string;fileName?:string;chars:number}};
function ars(n?:number|null){if(typeof n!=='number'||!Number.isFinite(n))return'No informado';return'$'+Math.round(n).toLocaleString('es-AR')}
function tone(score:number){if(score>=80)return'danger';if(score>=60)return'warn';if(score>=35)return'mid';return'safe'}
function sev(s?:string){return s==='Alta'?'sev alta':s==='Baja'?'sev baja':'sev media'}
function barStyle(score?:number){return{width:`${Math.max(0,Math.min(100,score||0))}%`}}
export default function Home(){
 const [text,setText]=useState('');const [file,setFile]=useState<File|null>(null);const [loading,setLoading]=useState(false);const [analysis,setAnalysis]=useState<Analysis|null>(null);const [error,setError]=useState('');
 async function analyze(){setLoading(true);setError('');setAnalysis(null);try{let body:BodyInit;let headers:HeadersInit|undefined; if(file){const fd=new FormData();fd.append('text',text);fd.append('file',file);body=fd}else{headers={'Content-Type':'application/json'};body=JSON.stringify({text})}const r=await fetch('/api/analyze',{method:'POST',headers,body});const j=await r.json();if(!r.ok)throw new Error(j.error||'No se pudo analizar');setAnalysis(j);setTimeout(()=>document.getElementById('resultado')?.scrollIntoView({behavior:'smooth',block:'start'}),80)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 async function pay(){const r=await fetch('/api/checkout',{method:'POST'});const j=await r.json();if(j.url)location.href=j.url;else alert(j.error||'No se pudo iniciar el pago')}
 return <main className="wrap">
  <nav className="nav"><div className="brand">Chamuyo<span className="gradient">Check</span></div><a className="pill" href="#analizar">Probar gratis</a></nav>
  <section className="heroV5">
   <div className="heroCopy"><span className="badge">V5 · Comité de auditoría prudente</span><h1 className="h1">Detecta el chamuyo <span className="gradient">sin acusar:</span> audita, calcula, pregunta y revisa PDF.</h1><p className="lead">Analiza promesas comerciales, préstamos, inversiones, contratos y trabajos académicos. El resultado no acusa: muestra indicadores, información faltante, cálculos, preguntas críticas y resguardo legal.</p><div className="trust"><span>✓ Resguardo legal</span><span>✓ PDF</span><span>✓ Cálculo financiero</span><span>✓ Radar piramidal</span><span>✓ Señales de posible IA</span></div></div>
   <div id="analizar" className="analyzerCard"><p className="small">Pegá texto o subí un PDF</p><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Pegá una propuesta, préstamo, contrato, publicación o trabajo académico..."/><label className="upload"><input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><span>{file?`PDF cargado: ${file.name}`:'Subir PDF para analizar'}</span></label><div className="cta"><button className="btn" onClick={analyze} disabled={loading||(!file&&text.length<20)}>{loading?'Analizando...':'Analizar con V5'}</button><button onClick={pay} className="btn secondary">Pasarme a Pro</button></div>{error&&<p className="err">{error}</p>}<p className="tiny">Para detectar posible IA en trabajos escolares o universitarios, el sistema solo da señales orientativas. No prueba autoría.</p></div>
  </section>
  {analysis&&<section id="resultado" className="analysisShell">
   <div className="resultHeader"><div><span className="badge">Resultado V5</span><h2>{analysis.documentType}</h2><p>{analysis.summary}</p>{analysis.source&&<p className="small">Fuente: {analysis.source.kind}{analysis.source.fileName?` · ${analysis.source.fileName}`:''} · {analysis.source.chars?.toLocaleString('es-AR')} caracteres</p>}</div><div className={`bigScore ${tone(analysis.score)}`}>{analysis.score}<small>/100</small></div></div>
   <div className="bar"><span style={barStyle(analysis.score)}/></div>
   <div className="decisionGrid"><div><span>Riesgo</span><b>{analysis.risk}</b></div><div><span>Confianza</span><b>{analysis.confidence}</b></div><div><span>Pregunta central</span><b>{analysis.decisionQuestion}</b></div></div>
   {analysis.verdict&&<div className="verdict"><b>Conclusión prudente:</b> {analysis.verdict}</div>}
   <div className="contentGrid">
    <section className="panel priority"><h3>Prioridad para decidir</h3><ul>{analysis.issues.slice(0,5).map((x,i)=><li key={i}>{x}</li>)}</ul></section>
    {analysis.financialMath?.detected&&<section className="panel financeBox"><h3>Inteligencia matemática financiera</h3><p>{analysis.financialMath.plainEnglish}</p><div className="financeGrid"><div><span>Monto</span><b>{ars(analysis.financialMath.amount)}</b></div><div><span>Cuota</span><b>{ars(analysis.financialMath.installment)}</b></div><div><span>Plazo</span><b>{analysis.financialMath.months?`${analysis.financialMath.months} meses`:'No informado'}</b></div><div><span>Total</span><b>{ars(analysis.financialMath.totalPaid)}</b></div><div><span>Costo extra</span><b>{ars(analysis.financialMath.hiddenCost)}</b></div><div><span>Tasa implícita</span><b>{analysis.financialMath.monthlyImpliedRate?`${analysis.financialMath.monthlyImpliedRate}% mensual`:'No calculable'}</b></div></div><p className="small"><b>Datos que faltan:</b> {analysis.financialMath.missingFields.join(', ')}</p></section>}
    {analysis.aiDetection?.detected&&<section className="panel aiBox"><h3>Posible redacción con IA</h3><div className="riskLine"><b>{analysis.aiDetection.risk}/100</b><span>Confianza: {analysis.aiDetection.confidence}</span></div><p>{analysis.aiDetection.explanation}</p><ul>{analysis.aiDetection.signals.map((x,i)=><li key={i}>{x}</li>)}</ul><p className="small"><b>Resguardo:</b> {analysis.aiDetection.legalNote}</p></section>}
    {analysis.pyramidRisk?.detected&&<section className="panel pyramidBox"><h3>Radar piramidal / Ponzi</h3><div className="riskLine"><b>{analysis.pyramidRisk.level}</b><span>{analysis.pyramidRisk.risk}/100</span></div><p>{analysis.pyramidRisk.explanation}</p><ul>{analysis.pyramidRisk.signals.map((x,i)=><li key={i}>{x}</li>)}</ul></section>}
   </div>
   {analysis.categoryScores?.length? <section className="full"><h3>Índices de auditoría</h3><div className="miniGrid">{analysis.categoryScores.map((c,i)=><div className="mini" key={i}><div className="miniTop"><b>{c.name}</b><span>{c.score}/100</span></div><div className="miniBar"><span style={barStyle(c.score)}/></div><p className="small">{c.explanation}</p></div>)}</div></section>:null}
   {analysis.modules?.length? <section className="full"><h3>Comité de análisis</h3><div className="moduleGrid">{analysis.modules.map((m,i)=><div className="module" key={i}><div className="miniTop"><b>{m.title}</b><span>{m.risk}/100</span></div><p>{m.summary}</p>{m.signals?.length?<ul>{m.signals.slice(0,3).map((x,j)=><li key={j}>{x}</li>)}</ul>:null}</div>)}</div></section>:null}
   <div className="contentGrid"><section className="panel"><h3>Preguntas para decidir mejor</h3><ul>{analysis.questions.map((x,i)=><li key={i}>{x}</li>)}</ul></section><section className="panel"><h3>Información faltante</h3><ul>{analysis.missingInformation?.map((x,i)=><li key={i}>{x}</li>)}</ul></section></div>
   {analysis.flaggedPhrases?.length?<section className="full"><h3>Frases bajo sospecha</h3><div className="phrases">{analysis.flaggedPhrases.map((f,i)=><div className="phrase" key={i}><span className={sev(f.severity)}>{f.severity}</span><p><b>“{f.phrase}”</b></p><p className="small">{f.problem}</p></div>)}</div></section>:null}
   <div className="contentGrid"><section className="panel"><h3>Peor escenario razonable</h3><p>{analysis.worstReasonableScenario}</p></section><section className="panel"><h3>Versión más transparente</h3><p>{analysis.improved}</p></section></div>
   {analysis.legalGuard&&<section className="legal"><h3>Resguardo legal del análisis</h3><p>{analysis.legalGuard.disclaimer}</p><p className="small">{analysis.legalGuard.prohibitedLanguagePolicy}</p></section>}
  </section>}
  <section className="grid"><div className="feature"><h3>Diseño equilibrado</h3><p>El resultado ya no queda encerrado a la derecha: se abre como tablero completo.</p></div><div className="feature"><h3>Subida de PDF</h3><p>Extrae texto de PDF y lo analiza con los mismos módulos.</p></div><div className="feature"><h3>Uso de IA en trabajos</h3><p>Detecta señales compatibles, pero no acusa ni prueba autoría.</p></div><div className="feature"><h3>Chamuyo financiero</h3><p>Calcula costo total visible, tasa implícita y omisiones críticas.</p></div></section>
 </main>
}
